QUESTION:
  https://www.hackerrank.com/challenges/sql-projects/problem

FUNCTIONS USED:
  CTE
  ROW_NUMBER()
  JOIN

QUERY:
WITH STDT AS (
             SELECT Start_Date,
                    ROW_NUMBER() OVER(ORDER BY START_DATE) RN
             FROM Projects WHERE START_DATE NOT IN (SELECT END_DATE FROM PROJECTS)
),
ENDDT AS (
    SELECT END_DATE,
                    ROW_NUMBER() OVER(ORDER BY END_DATE) RN
             FROM Projects WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS)
)
SELECT START_DATE, END_DATE
FROM STDT JOIN ENDDT ON ENDDT.RN = STDT.RN
ORDER BY (END_DATE-START_DATE),1;
